
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: chatbot-api
    ports:
      - 8000:8000
    env_file:
      - .env
    secrets:
      - openai_api_key
      - langsmith_api_key
    networks:
      - chatbot-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - chatbot-network
    restart: always

secrets:
  openai_api_key:
    file: ./oa_api_key.txt
  langsmith_api_key:
    file: ./ls_api_key.txt

networks:
  chatbot-network:
    driver: bridge
