
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: chatbot-api
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - chatbot-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - chatbot-network
    restart: always


networks:
  chatbot-network:
    driver: bridge
